# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: RunnerTrial

    steps:
    - uses: actions/checkout@v3
    - name: Install Node JS
      run: |
        sudo apt update
        sudo apt install nodejs
    
    - name: Create React App
      run: npx create-react-app App/

    - name: Update File Structure
      run: |
        rm -rf App/public 
        rm -rf App/src
        rm -rf App/package.json
        cp react-frontend/* App/

    - name: Install Dependencies
      run: |
        npm install redux
        npm install ui

    - name: Build
      run: npm run build